### ISSUE TITLE
Cannot start the program

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#24]
Hi,

As a gamer, I am checking out Eamon-CS on my windows 10 pc. Unfortunately, I cannot get it to run. Perhaps I am doing something wrong? I go to the quicklaunch->windows->EamonMH and double-click "EnterMainHallUsingAdventures.bat". Then a window opens and closes extremely fast and that's it.

Can you help?
Thanks.

**Comment by firstmethod** [comment]
Hi,


Sorry about the difficulties here... The solution to this is pretty easy but perhaps not obvious.


You need to obtain and install both .NET Framework 4.6.1+ and .NET Core 2.0+.


Actually, both the downloads you need can be found right here:  https://www.microsoft.com/net/download/windows


Download one of the selections under the .NET Framework heading and install it.


Then download one of the selections under the .NET Core heading and install it.


If you are a developer who wishes to experiment with the source code, you should download the SDK and Developer Packs:


[cid:c1d80c94-26b1-4bf9-87b2-5c5146fcb81e]


If you are a gamer then you should probably just download the Runtimes:


[cid:5184c0e5-7112-4f48-93a6-0a7e9bbdc93a]


(Note:  these are just illustrative pictures, you still need to go to https://www.microsoft.com/net/download/windows to download them)


If you still have problems, please let me know.


Thanks,

M. Penner


[https://www.microsoft.com/net/images/redesign/social/square.png]<https://www.microsoft.com/net/download/windows>

.NET Downloads for Windows - microsoft.com<https://www.microsoft.com/net/download/windows>
www.microsoft.com
Free downloads for building and running .NET applications on Linux, macOS, Windows. Downloads for .NET Core, .NET Framework, Visual Studio, and more.




[https://www.microsoft.com/net/images/redesign/social/square.png]<https://www.microsoft.com/net/download/windows>

.NET Downloads for Windows - microsoft.com<https://www.microsoft.com/net/download/windows>
www.microsoft.com
Free downloads for building and running .NET applications on Linux, macOS, Windows. Downloads for .NET Core, .NET Framework, Visual Studio, and more.




________________________________

**Comment by firstmethod** [comment]
Sorry, please disregard the previous message...  Those links on Microsoft are bad... here are the proper links:


If you're a developer please download and install the following in order:


https://www.microsoft.com/net/download/thank-you/net472-developer-pack
https://www.microsoft.com/net/download/thank-you/dotnet-sdk-2.1.302-windows-x64-installer


If you're a gamer please download and install the following in order:


https://www.microsoft.com/net/download/thank-you/net472-offline

https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.2-windows-x64-installer



If you have any issues, please let me know,

M. Penner



________________________________

**Comment by kpeamon** [comment]
That helped - Eamon is running smoothly now  :-)
