### ISSUE TITLE
Request - Crypt Crashers

### ISSUE THREAD

**Issue by jpsanders64** [firstmethod/Eamon-CS#27]
Any chance you could port your 'Crypt Crashers' over to this version of Eamon?  Enjoyed it years ago and wouldn't mind giving it another go.

**Comment by firstmethod** [comment]
Hi jpsanders64,

Thanks for your interest and kind words!  The short answer to your question is a qualified yes!  The qualification being there are some technical hurdles to overcome on that particular title.  

First, the source code is in some crazy tokenized GFA Basic format which is tricky to access.  I HAVE gotten to it in the last few years but it was a real pain and the particulars on how to do so have slipped my mind at this point.  I remember I had to try multiple versions of GFA 3.0 before I found one that worked.  Assuming that version is still out there it seems reasonable I could get to the source code again.

The second hurdle is this game was a technical beast.  It had been put on the backburner purposely until the game engine went through enough revisions to support it.  I believe the ECS system is up to the task at this point, however.  Porting it will probably be a drawn out process.

The last hurdle is I can't bring myself to port the game verbatim - there will need to be changes to the content.  Some areas just haven't held up well to my scrutiny.

It appears the development schedule is booked through the end of the year.  2019 is likely to be a "year of content" and I will put Crypt Crashers (which will be renamed) at the top of the list.  I will try to get access to the source code ASAP to at least ensure its possible.  I'll leave this ticket open and plan to get back to you with my findings, but it could be weeks or months.

Regards,
M. Penner
