### ISSUE TITLE
Eamon Game requests

### ISSUE THREAD

**Issue by kpeamon** [firstmethod/Eamon-CS#31]
Hi, besides letting you know that I am looking forward to future Eamon CS games, I would like to give some game requests. Recently I wanted to play through all those Eamon games, which could be played without an Apple II emulator, i.e. the games available through Eamon Remastered, Eamon Deluxe 5.0 and PC Eamon Museum. 

More than 80 games were not available. Thus I checked if Eamon CS had some adventures covered, which were not covered by the other Windows compatible Eamon systems. Eamon CS had only one finished game I hadn't played. That was "Wrenhold's Secret Vigil". I played it and it was a very fine game and showed that Eamon CS is a good system.

So I hope you will focus on those games which are not available elsewhere. They are listed below. Several of these are highly rated at eamonag.org.

The games, which are not available through Eamon Remastered, Eamon Deluxe 5.0 and PC Eamon Museum are:

* The Vile Grimoire of Jaldial	Eamon CS
* The Wayfarer's Inn		Eamon CS
* Grunewalde 			(Pat Hurst)
* The Pyramid of Anharos 	(Pat Hurst)
* Buccaneer! 			(Pat Hurst)
* The Dark Brotherhood 		(Pat Hurst)
* The Hunt for the Ring (Sam Ruby)
* The Quest of Erebor 	(Sam Ruby)
* Return to Moria 	(Sam Ruby)
* Haradwaith 		(Sam Ruby)
* Elemental Apocalypse 	(Sam Ruby)
* Animal Farm 		(Sam Ruby)
* The Boy and the Bard 	(Sam Ruby)
* Sanctuary 		(Sam Ruby)
* Assault on Dolni Keep		(Tom Zuchowski)
* Journey to Jotunheim		(Tom Zuchowski)
* Walled City of Darkness	(Tom Zuchowski)
* Hammer's Slammers		(Tom Zuchowski)
* City in the clouds		(Best of the Classic Adventures)
* The Deep Canyon		(Best of the Classic Adventures)
* Temple of the Guild		(Best of the Classic Adventures)
* The Search for Yourself	(Best of the Classic Adventures)
* The Fugitive			(Best of the Classic Adventures)
* Camp Eamon			(Best of the Classic Adventures)
* Pittfall			(Best of the Classic Adventures)
* Peg's Place			(Best of the Classic Adventures)
* The House of Secrets 			(Classic Eamon Adventures Vol. 3)
* Slave Pits of Kzorland 		(Classic Eamon Adventures Vol. 3)
* Fire Island 				(Classic Eamon Adventures Vol. 3)
* Vacation in Europe 			(Classic Eamon Adventures Vol. 3)
* Hills of History 			(Classic Eamon Adventures Vol. 3)
* The Wizard of the Spheres 		(Classic Eamon Adventures Vol. 3)
* Nucleus of the Ruby 			(Classic Eamon Adventures Vol. 3)
* The Final Frontier 			(Classic Eamon Adventures Vol. 3)
* Pyramid of the Ancients 		(Classic Eamon Adventures Vol. 3)
* The Ruins of Ivory Castle 		(Classic Eamon Adventures Vol. 3)
* Starfire 				(Classic Eamon Adventures Vol. 3)
* The Infested Fortress 		(Classic Eamon Adventures Vol. 3)
* Gartin Manor 				(Classic Eamon Adventures Vol. 3)
* Expedition to the Darkwoods 		(Classic Eamon Adventures Vol. 3)
* The Beermeister's Brewery	(Classic Eamon Adventures Vol. 4)
* The Alternate Zone		(Classic Eamon Adventures Vol. 4)
* The House of Horrors		(Classic Eamon Adventures Vol. 4)
* Eamon S.A.R.-1:The Deneb Raid (Classic Eamon Adventures Vol. 4)
* A Trip to Fort Scott 		(Classic Eamon Adventures Vol. 4)
* Tomb of the Vampire 		(Classic Eamon Adventures Vol. 4)
* The Sands of Mars 		(Classic Eamon Adventures Vol. 4)
* A real Cliffhanger 		(Classic Eamon Adventures Vol. 4)
* The High School of Horrors	(Classic Eamon Adventures Vol. 4)
* Mountain of the Master	(Classic Eamon Adventures Vol. 4)
* Quest for Orion		(Classic Eamon Adventures Vol. 4)
* Shift Change at Grimmwax	(Classic Eamon Adventures Vol. 4)
* Mean Streets			(Classic Eamon Adventures Vol. 4)
* Quest of the Crystal Wand	(Classic Eamon Adventures Vol. 4)
* The Lost Isle			(Classic Eamon Adventures Vol. 4)
* The Caverns of Vanavara	(Classic Eamon Adventures Vol. 4)
* The Plain of Srevi		(Classic Eamon Adventures Vol. 4)
* Lotto's Masterpiece		(Classic Eamon Adventures Vol. 4)
* Utterly Outrageous		(Classic Eamon Adventures Vol. 4)
* Vaalpa's Plight		(Classic Eamon Adventures Vol. 4)
* Eamon Renegade Club		  (Classic Eamon Adventures Vol. 5)
* Assault on Helstar		  (Classic Eamon Adventures Vol. 5)
* Apocalypse 2021		  (Classic Eamon Adventures Vol. 5)
* Return of Ngurct		  (Classic Eamon Adventures Vol. 5)
* Lair of the Marauders		  (Classic Eamon Adventures Vol. 5)
* Haunted Keep			  (Classic Eamon Adventures Vol. 5)
* Deathstalker's Castle		  (Classic Eamon Adventures Vol. 5)
* Eye of Agamon			  (Classic Eamon Adventures Vol. 5)
* Return to Pendrama		  (Classic Eamon Adventures Vol. 5)
* The City of Sorcerers		  (Classic Eamon Adventures Vol. 5)
* Catacombs of Terror		  (Classic Eamon Adventures Vol. 5)
* Time-Shift			  (Classic Eamon Adventures Vol. 5)
* Prisoner of Darkness		  (Classic Eamon Adventures Vol. 5)
* Shipwreck Island		  (Classic Eamon Adventures Vol. 5)
* Firestorm			  (Classic Eamon Adventures Vol. 5)
* Well of the Great Ones	  (Classic Eamon Adventures Vol. 5)
* Keep of Skull Gorge		  (Classic Eamon Adventures Vol. 5)
* Jewel of Yara			  (Classic Eamon Adventures Vol. 5)
* The Domain of Zenoqq		  (Classic Eamon Adventures Vol. 5) 
* The Pixy Oak 		(Classic Eamon Adventures Vol. 6)
* The Prism of Shadows 	(Classic Eamon Adventures Vol. 6)
* Dawn of the Warlock 	(Classic Eamon Adventures Vol. 6)
* Tenement of the Damned	(The Lost Treasures of Eamon)

**Comment by firstmethod** [comment]
Greetings kpeamon,

Thanks for your long-running interest in the Eamon CS system, I am glad to hear you played through and enjoyed Wrenhold's Secret Vigil.  Bob Davis really hit it out of the park with both of his Eamons; I think they are masterpieces.

In the future, when I port existing Eamons I will definitely give weight to that list.  In fact, I see a pair of Eamons that I started porting a year or two ago (The Pyramid of Anharos and Firestorm) but shelved back then due to ongoing game-engine related work.  I will probably revisit them if I don't find anything more suitable.  As a side note, I would also mention that I cannot rule out porting what I would call elite Eamons, regardless of whether a modern version exists (The Prince's Tavern comes immediately to mind).  But beyond that, I'll consult the list.

I know it has been a long, dry 2-year stretch with no new content.  But - good news - the wait is over, as of 5 minutes ago I just checked in the final changes to the Eamon CS base game engine (there may be bug fixes or improvements in the future, but what's in Github is what I had always envisioned.)  After a week of testing, it gets pushed into master branch, and I'm back on The Vile Grimoire of Jaldi'al.  Then onto The Wayfarer's Inn.  Please let me know if you have any further comments or questions!

Thanks again,
M. Penner

**Comment by kpeamon** [comment]
Good to hear that things are moving forward! Should you need a game-tester, I will be happy to help.
Best regards
Ken
